language: python
python:
  - "2.6"
  - "2.7"
install: "pip install psycopg2"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - psql -f vagrant/tournament/tournament.sql
  - python vagrant/tournament/tournament_test.py